import mongoose from 'mongoose';
import { FixReport, Repo } from '../models/index.js';
import { createRealPullRequest } from '../utils/githubHelper.js';

export async function detectAutoFixes(repoId, categories = ['Formatting', 'Unused Imports', 'Lint Errors'], userId) {
  if (!userId || !repoId || !mongoose.Types.ObjectId.isValid(repoId)) {
    throw { statusCode: 404, message: 'Repository not found' };
  }
  const repo = await Repo.findOne({ _id: repoId, userId });
  if (!repo) {
    throw { statusCode: 404, message: 'Repository not found' };
  }

  const existing = await FixReport.findOne({ repoId, userId }).sort({ createdAt: -1 });
  if (existing) return existing;

  const fixes = [
    {
      id: 'fix_1',
      filePath: 'src/index.js',
      category: 'Unused Imports',
      explanation: 'Remove unused import statements detected during scanning',
      before: `import React, { useState, useEffect } from 'react';`,
      after: `import React, { useState } from 'react';`,
      selected: true
    }
  ];

  const report = await FixReport.create({
    repoId,
    userId,
    issuesFoundCount: fixes.length,
    fixes
  });

  return report;
}

export async function createFixPR(repoId, selectedFixIds, userId) {
  if (!userId || !repoId || !mongoose.Types.ObjectId.isValid(repoId)) {
    throw { statusCode: 404, message: 'Repository not found' };
  }
  const repo = await Repo.findOne({ _id: repoId, userId });
  if (!repo) {
    throw { statusCode: 404, message: 'Repository not found' };
  }

  const fixReport = await FixReport.findOne({ repoId, userId }).sort({ createdAt: -1 });
  const selectedFixes = fixReport?.fixes?.filter(f => !selectedFixIds || selectedFixIds.length === 0 || selectedFixIds.includes(f.id)) || [];
  const count = selectedFixes.length;

  const firstFix = selectedFixes[0] || { filePath: 'src/index.js', after: '// RepoSense auto-fix applied\n' };

  return await createRealPullRequest({
    userId,
    repo,
    branchName: `reposense/fix-${Date.now()}`,
    filePath: firstFix.filePath || 'src/index.js',
    content: firstFix.after || '// RepoSense auto-fix applied\n',
    commitMessage: `fix: auto-fix ${count || 1} linting & import issues via RepoSense`,
    prTitle: `fix: apply ${count || 1} codebase auto-fixes via RepoSense AI`,
    prBody: `Applied ${count || 1} structural auto-fixes generated by RepoSense AI.`
  });
}
