import mongoose from 'mongoose';
import { ReadmeVersion, Repo } from '../models/index.js';
import { executeAiQuery } from '../utils/llmRouter.js';
import { evaluateReadmeQuality } from '../utils/heuristics.js';
import { createRealPullRequest } from '../utils/githubHelper.js';

export async function generateReadmeContent({ repoId, repoName, tone = 'Professional', sections = [], language = 'English', customInstruction = '', userId }) {
  if (!userId || !repoId || !mongoose.Types.ObjectId.isValid(repoId)) {
    throw { statusCode: 404, message: 'Repository not found' };
  }
  const repo = await Repo.findOne({ _id: repoId, userId });
  if (!repo) {
    throw { statusCode: 404, message: 'Repository not found' };
  }

  const prompt = `Generate a complete, production-ready, beautifully formatted GitHub README.md for the project "${repo.name}".
Tone: ${tone}. Language: ${language}.
Included Sections: ${sections.join(', ') || 'Title, Description, Tech Stack, Installation, Usage, License'}.
${customInstruction ? `Special Instructions: ${customInstruction}` : ''}

Output strictly valid Markdown headers and code blocks.`;

  const aiResult = await executeAiQuery({ prompt });
  let markdown = aiResult.text;
  markdown = markdown.replace(/^```markdown\n/, '').replace(/^```\n/, '').replace(/\n```$/, '');

  const evalRes = evaluateReadmeQuality(markdown);

  await ReadmeVersion.create({
    repoId,
    userId,
    content: markdown,
    tone,
    sectionsIncluded: sections,
    language
  });

  repo.hasReadme = true;
  repo.readmeQualityScore = evalRes.score;
  await repo.save();

  return markdown;
}

export async function commitReadmePR({ repoId, content, branchName = 'reposense/update-readme', commitMessage = 'docs: add auto-generated README.md via RepoSense', userId }) {
  let repo = null;
  if (repoId && mongoose.Types.ObjectId.isValid(repoId)) {
    repo = await Repo.findOne({ _id: repoId, userId });
  }

  if (!repo) {
    throw { statusCode: 404, message: 'Repository not found' };
  }

  return await createRealPullRequest({
    userId,
    repo,
    branchName,
    filePath: 'README.md',
    content,
    commitMessage,
    prTitle: 'docs: update README.md via RepoSense AI',
    prBody: 'Automated documentation update generated by RepoSense AI.'
  });
}

export async function getReadmeHistory(repoId, userId) {
  if (!userId || !repoId || !mongoose.Types.ObjectId.isValid(repoId)) return [];
  const repo = await Repo.findOne({ _id: repoId, userId });
  if (!repo) return [];

  return await ReadmeVersion.find({ repoId, userId }).sort({ createdAt: -1 });
}
